Handle diffs with files renamed, moved or copied
trassir/hg-phabdiff pull request #14
Opened 2020-12-07 14:22 UTC by worldemar

2020-12-07 15:12 UTC, Artalus requested changes

2020-12-07 15:12 UTC, Artalus commented on hg-phabdiff/plugin.py
> +            '--clean'
думаю, здесь лучше делать `hg revert --all`, чтобы не спровоцировать случайно рекурсивное `hg update`

2020-12-07 15:12 UTC, Artalus commented on hg-phabdiff/plugin.py
> +            EXE_HG(), 'id', '--id', '-T', '{id}',
вроде `--id` здесь лишнее, ведь выхлоп форматируется через `-T`?

2020-12-07 15:12 UTC, Artalus commented on hg-phabdiff/plugin.py
> +    _, commit_id = p.communicate()
> `communicate()` returns a tuple `(stdoutdata, stderrdata)`. [(c)](https://docs.python.org/2.7/library/subprocess.html#subprocess.Popen.communicate)

`hg id` возвращает результат через stderr? :thinking:

2020-12-07 16:11 UTC, worldemar commented on hg-phabdiff/plugin.py
> +            '--clean'
заменил, по результату вроде то же самое

2020-12-07 16:12 UTC, worldemar commented on hg-phabdiff/plugin.py
> +            EXE_HG(), 'id', '--id', '-T', '{id}',
паранойя, да. но с `revert` оно не нужно вовсе

2020-12-07 16:12 UTC, worldemar commented on hg-phabdiff/plugin.py
> +    _, commit_id = p.communicate()
ну вобще-то да 🤷 
удалил

2020-12-07 16:27 UTC, Artalus approved these changes

2020-12-08 09:04 UTC, mm0d approved these changes

2020-12-10 08:32 UTC, merged